# Generated by Django 4.1.5 on 2023-01-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[("JR", "Junior"), ("MD", "Middle"), ("SR", "Senior")],
                        default="JR",
                        max_length=2,
                    ),
                ),
                ("status", models.CharField(max_length=50)),
                ("specialty", models.CharField(max_length=50)),
                ("salary", models.IntegerField()),
                ("education", models.CharField(max_length=50)),
                ("experience", models.CharField(max_length=50)),
                ("portfolio", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
